//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class budget
    {
        public int id_action { get; set; }
        public Nullable<bool> kind_of_action { get; set; }
        public string action_desription { get; set; }
        public Nullable<System.DateTime> action_date { get; set; }
        public Nullable<decimal> action_sum { get; set; }
    }
}
