//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Building_ManangementEntities : DbContext
    {
        public Building_ManangementEntities()
            : base("name=Building_ManangementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<budget> budget { get; set; }
        public virtual DbSet<Building> Building { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Common_Space> Common_Space { get; set; }
        public virtual DbSet<Meeting> Meeting { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Resident> Resident { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Volunteering> Volunteering { get; set; }
        public virtual DbSet<Professonal> Professonal { get; set; }
    }
}
