//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int id_request { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string tz { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public Nullable<int> street_num { get; set; }
        public Nullable<int> apartment_num { get; set; }
        public Nullable<int> floor_num { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Status Status1 { get; set; }
    }
}
