//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int id_action { get; set; }
        public Nullable<bool> kind_of_action { get; set; }
        public string action_description { get; set; }
        public Nullable<System.DateTime> action_date { get; set; }
        public Nullable<int> action_sum { get; set; }
        public Nullable<int> id_tenant { get; set; }
        public Nullable<int> id_building { get; set; }
        public Nullable<int> id_action_category { get; set; }
    
        public virtual Action_Category Action_Category { get; set; }
        public virtual Building Building { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
