//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_Space
    {
        public int id_common_space { get; set; }
        public Nullable<int> id_building { get; set; }
        public string activity_days { get; set; }
        public string activity_hours { get; set; }
        public string schedule { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
