//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id_comment { get; set; }
        public int id_meeting { get; set; }
        public int id_tenant { get; set; }
        public string comment_description { get; set; }
        public System.DateTime comment_date { get; set; }
        public int id_building { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Meeting Meeting { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
