//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Building_ManangementEntities : DbContext
    {
        public Building_ManangementEntities()
            : base("name=Building_ManangementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<Action_Category> Action_Category { get; set; }
        public virtual DbSet<Building> Building { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Common_Space> Common_Space { get; set; }
        public virtual DbSet<experience> experience { get; set; }
        public virtual DbSet<Meeting> Meeting { get; set; }
        public virtual DbSet<Meeting_vote> Meeting_vote { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Professonal> Professonal { get; set; }
        public virtual DbSet<Professonal_Category> Professonal_Category { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tenant> Tenant { get; set; }
        public virtual DbSet<TenantManager_Messeage> TenantManager_Messeage { get; set; }
        public virtual DbSet<Volunteer> Volunteer { get; set; }
        public virtual DbSet<Volunteering> Volunteering { get; set; }
        public virtual DbSet<Volunteering_Category> Volunteering_Category { get; set; }
        public virtual DbSet<Vote> Vote { get; set; }
    }
}
