//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int id_payment { get; set; }
        public int id_tenant { get; set; }
        public System.DateTime payment_date { get; set; }
        public int payment_month { get; set; }
        public bool done { get; set; }
        public Nullable<int> payment_sum { get; set; }
        public int id_building { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
