//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantManager_Messeage
    {
        public int id_tenantManager_messeage { get; set; }
        public int? id_tenantManager { get; set; }
        public int id_building { get; set; }
        public string description_tenantManager_messeage { get; set; }
        public System.DateTime tenantManager_messeage_date { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
