//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        public int id_volunteer { get; set; }
        public Nullable<int> id_building { get; set; }
        public Nullable<int> id_tenant { get; set; }
        public int id_volunteering { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public Nullable<bool> done { get; set; }
    
        public virtual Tenant Tenant { get; set; }
        public virtual Tenant Tenant1 { get; set; }
        public virtual Tenant Tenant2 { get; set; }
        public virtual Volunteering Volunteering { get; set; }
    }
}
