//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int id_vote { get; set; }
        public int id_meeting { get; set; }
        public string vote_subject { get; set; }
        public string vote_description { get; set; }
        public string tenants_vote { get; set; }
        public int id_building { get; set; }
        public Nullable<int> id_tenant { get; set; }
        public Nullable<int> id_vote_meeting { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Meeting Meeting { get; set; }
        public virtual Meeting_vote Meeting_vote { get; set; }
    }
}
